export const TEXT_NODE = 3;
export const ATTRIBUTE_NODE = 2;
export const ELEMENT_NODE = 1;

export const BREAK_LINE = 'BR';

export const IMMEDIATELY_EDITOR_COMMAND = 3;
export const HIGH_EDITOR_COMMAND = 2;
export const STANDART_EDITOR_COMMAND = 1;
export const IGNOREMANAGER_EDITOR_COMMAND = 10;

export const EDITOR_PRIORITY = {
	IMMEDIATELY_EDITOR_COMMAND: 3,
	HIGH_EDITOR_COMMAND: 2,
	STANDART_EDITOR_COMMAND: 1,
	IGNOREMANAGER_EDITOR_COMMAND: 10,
};
